.TH GF2-AMP 1
.SH NAME
gf2-amp \- set GF2 Function Generator amplitude to a given value
.SH SYNOPSIS
.B gf2-amp
.I AMPLITUDE
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B gf2-amp
sets the amplitude to the value given in the argument. This value is expressed
in Vpp (or Volts peak-to-peak) and must be between 0 and 8, inclusive. Decimal
values are accepted.

Specifying a serial number is optional.
.SH EXAMPLE
.TP
.B gf2-amp 6.4
Set the amplitude to 6.4Vpp.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur, or two in case of bad input.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
gf2-amp50(1), gf2-clear(1), gf2-clkoff(1), gf2-clkon(1), gf2-dacoff(1),
gf2-dacon(1), gf2-freq(1), gf2-freq0(1), gf2-freq1(1), gf2-list(1),
gf2-lockotp(1), gf2-phase(1), gf2-phase0(1), gf2-phase1(1), gf2-reset(1),
gf2-selfreq0(1), gf2-selfreq1(1), gf2-selphase0(1), gf2-selphase1(1),
gf2-sine(1), gf2-start(1), gf2-status(1), gf2-stop(1), gf2-tri(1)
