.TH GF2-FREQ 1
.SH NAME
gf2-freq \- set GF2 Function Generator frequency to a given value
.SH SYNOPSIS
.B gf2-freq
.I FREQUENCY
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B gf2-freq
sets the frequency to the value given in the argument. This value is expressed
in KHz and must be between 0 and 40000, inclusive. Decimal values are
accepted. Note that this command will always take effect over the frequency of
the output signal, because it changes the currently selected frequency
parameter (i.e., frequency 0 or frequency 1). If you care about which
frequency parameter is being changed, you should use
.B gf2-freq0
or
.B gf2-freq1
instead, or pre-select the active frequency parameter by invoking
.B gf2-selfreq0
or
.B gf2-selfreq1
before calling
.BR gf2-freq .

Specifying a serial number is optional.
.SH EXAMPLE
.TP
.B gf2-freq 15.3
Set the frequency to 15.3KHz.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur, or two in case of bad input.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
gf2-amp(1), gf2-amp50(1), gf2-clear(1), gf2-clkoff(1), gf2-clkon(1),
gf2-dacoff(1), gf2-dacon(1), gf2-freq0(1), gf2-freq1(1), gf2-info(1),
gf2-list(1), gf2-lockotp(1), gf2-phase(1), gf2-phase0(1), gf2-phase1(1),
gf2-reset(1), gf2-selfreq0(1), gf2-selfreq1(1), gf2-selphase0(1),
gf2-selphase1(1), gf2-sine(1), gf2-start(1), gf2-status(1), gf2-stop(1),
gf2-tri(1)
