.TH GF2-CLKOFF 1
.SH NAME
gf2-clkoff \- disable GF2 Function Generator synchronous clock
.SH SYNOPSIS
.B gf2-clkoff
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B gf2-clkoff
disables the synchronous clock. It is important to mention that the digital
output of the function generator will be inactive after invoking this command.
To re-enable the synchronous clock, invoke
.BR gf2-clkon .
You can verify the synchronous clock status by calling
.BR gf2-status .

Specifying a serial number is optional.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
gf2-amp(1), gf2-amp50(1), gf2-clear(1), gf2-clkon(1), gf2-dacoff(1),
gf2-dacon(1), gf2-freq(1), gf2-freq0(1), gf2-freq1(1), gf2-info(1),
gf2-list(1), gf2-lockotp(1), gf2-phase(1), gf2-phase0(1), gf2-phase1(1),
gf2-reset(1), gf2-selfreq0(1), gf2-selfreq1(1), gf2-selphase0(1),
gf2-selphase1(1), gf2-sine(1), gf2-start(1), gf2-status(1), gf2-stop(1),
gf2-tri(1)
