.TH GF2-SELFREQ1 1
.SH NAME
gf2-selfreq1 \- select frequency 1 as the active frequency parameter of GF2
Function Generator
.SH SYNOPSIS
.B gf2-selfreq1
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B gf2-selfreq1
selects the frequency 1 parameter to be the active frequency parameter of the
function generator. Along with
.BR gf2-selfreq0 ,
.B gf2-selfreq1
allows you to instantly switch between two frequency values during signal
generation, being a way to implement BFSK (binary frequency-shift keying). You
can use
.B gf2-freq0
and
.B gf2-freq1
to define the frequency parameters beforehand.

Specifying a serial number is optional.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
gf2-amp(1), gf2-amp50(1), gf2-clear(1), gf2-clkoff(1), gf2-clkon(1),
gf2-dacoff(1), gf2-dacon(1), gf2-freq(1),  gf2-freq0(1), gf2-freq1(1),
gf2-list(1), gf2-lockotp(1), gf2-phase(1), gf2-phase0(1), gf2-phase1(1),
gf2-reset(1), gf2-selfreq0(1), gf2-selphase0(1), gf2-selphase1(1),
gf2-sine(1), gf2-start(1), gf2-status(1), gf2-stop(1), gf2-tri(1)
